# ======= run mode =======
mode: inference          # inference | finetune | lora

# ======= runtime ========
output_dir: outputs/vggt_eval
inference:
  ddp: true                # ← 开启 DDP 推理（用 torchrun 启动） torchrun --nproc_per_node=4 infer.py -c path/to/your.yaml
  ddp_backend: nccl         # 单机多卡常用 nccl
  ddp_timeout_mins: 60
  max_img_per_gpu: 32       # ← 可选：推理阶段也显式限制“每步送入的帧数上限”
  only_rank0_visual: true   # ← 仅 rank0 做可视化与总汇总，避免多进程抢 IO
  rank_output_subdir: true  # ← 其它 rank 写入 sequence_dir/rank{N}/ 以防冲突
  gather: gather_object     # ← 跨 rank 汇总方式：gather_object | none
device: auto             # auto/cuda/cpu
amp:
  enabled: true
  dtype_policy: auto     # auto/bfloat16/float16/float32

# ======= model ==========
model:
  pretrained_id: facebook/VGGT-1B   # 先拉骨干（结构/默认权重）
  resume: null    # 可为 .pth/.pt/.safetensors 或包含权重的目录
  strict: false                     # 头不一致时建议 false

# ======= dataset ========
dataset:
  name: c3vd_v1
  root: /data/C3VD/C3VDv1/registered
  config_file: custom_dataset.yaml   # ← 二级 YAML 文件名，放在主 YAML 同目录
  use_registered: true
  min_num_images: 2
  assume_pose: w2c            # 可选：你的 pose.txt 是 w2c 还是 c2w
  depth_unit_scale: 0.001     # 可选：比如毫米→米就 0.001
  limit_seqs: -1

# ======= evaluation =====
evaluation:
  camera:
    enabled: true
    gt_pose_format: w2c          # 或 c2w
    align: sim3                  # 支持: none | se3 | sim3 | scale
    # 也支持多种一起评: ["none", "se3", "sim3"]
    plot_3d: true
    rpe_delta: 1
    rpe_delta_unit: frames       # frames | seconds
  depth:
    enabled: true
    align: median
    min_depth: 0.001
    max_depth: 80.0


# ======= visualization ==
visualization:
  camera_path:
    enabled: true
    save_3d_plot: true
  video_overlay:
    enabled: true
    fps: 10
    draw_traj: true
    draw_cam_axis: true
    axis_len: 40

# ======= finetune (placeholders; future) =======
train:
  epochs: 5
  log_interval: 10
  eval_interval: 1
  ckpt_interval: 1

optim:
  type: adamw
  lr: 2.0e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]

sched:
  type: cosine        # cosine | step | none
  warmup_steps: 8000
  step_size: 1
  gamma: 0.1

train_dataloader:
  batch_size: 1       # 多帧模型常用按“帧组”为1再在样本内堆帧
  num_workers: 8
  shuffle: true
  # 供训练 loader 使用的自定义项（示例）
  frames_per_sample: 8
  random_stride: [1, 3]
  augment:
    color_jitter: true
    blur: true
    gray: true
    aspect_ratio_range: [0.33, 1.0]
    resize_max: 518

eval_dataloader:
  batch_size: 1
  num_workers: 4
  shuffle: false
